name: 'Publish'


on:
  workflow_dispatch: # To can dispatch manually

  push:
    branches:
      - main



jobs:

  test-semantic:
    name: "Testing..."
    runs-on: 'ubuntu-latest'

    steps:
    - name: Semantic Release
      id: 'semantic-release'
      uses: cycjimmy/semantic-release-action@v3.4.2
      with:
        semantic_version: 19.0.5
        extra_plugins: |
          semantic-release-plugin-csproj
          @semantic-release/changelog
          @semantic-release/git
#          @semantic-release/github
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: "Debug"
      run: |
        echo ${{ steps.semantic.outputs.new_release_version }}
        echo ${{ steps.semantic.outputs.new_release_major_version }}
        echo ${{ steps.semantic.outputs.new_release_minor_version }}
        echo ${{ steps.semantic.outputs.new_release_patch_version }}
        echo ${{ steps.semantic.outputs.new_release_published }}
