name: 'Publish'


on:
  workflow_dispatch: # To can dispatch manually

  push:
    branches:
      - main



jobs:

  test-semantic:
    name: "Testing..."
    runs-on: 'ubuntu-latest'

    steps:
    - name: Semantic Release
      id: 'semantic-release'
      uses: cycjimmy/semantic-release-action@v3.4.1
      with:
        semantic_version: 19.0.5
        extra_plugins: |
          semantic-release-plugin-csproj
#          @semantic-release/changelog
#          @semantic-release/github
#          @semantic-release/git
#      env:
#        GH_TOKEN: ${{ secrets.GH_TOKEN }}
#        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
